# Generated by Django 5.2.7 on 2026-08-31 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0012_announcement'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancesession',
            name='rotation_interval',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='attendancesession',
            name='totp_secret',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
